// Script to add all remaining Indian states to location API
// Run with: npx tsx scripts/add-all-states.ts

const remainingStates = {
    Manipur: {
        cities: [
            "Imphal",
            "Thoubal",
            "Bishnupur",
            "Churachandpur",
            "Kakching",
            "Ukhrul",
            "Senapati",
            "Tamenglong",
            "Chandel",
            "Jiribam",
        ],
        districts: [
            "Bishnupur",
            "Chandel",
            "Churachandpur",
            "Imphal East",
            "Imphal West",
            "Jiribam",
            "Kakching",
            "Kamjong",
            "Kangpokpi",
            "Noney",
            "Pherzawl",
            "Senapati",
            "Tamenglong",
            "Tengnoupal",
            "Thoubal",
            "Ukhrul",
        ],
    },
    Meghalaya: {
        cities: [
            "Shillong",
            "Tura",
            "Nongstoin",
            "Jowai",
            "Baghmara",
            "Williamnagar",
            "Nongpoh",
            "Mairang",
            "Resubelpara",
        ],
        districts: [
            "East Garo Hills",
            "East Jaintia Hills",
            "East Khasi Hills",
            "North Garo Hills",
            "Ri Bhoi",
            "South Garo Hills",
            "South West Garo Hills",
            "South West Khasi Hills",
            "West Garo Hills",
            "West Jaintia Hills",
            "West Khasi Hills",
        ],
    },
    Mizoram: {
        cities: [
            "Aizawl",
            "Lunglei",
            "Champhai",
            "Serchhip",
            "Kolasib",
            "Lawngtlai",
            "Saiha",
            "Mamit",
        ],
        districts: [
            "Aizawl",
            "Champhai",
            "Kolasib",
            "Lawngtlai",
            "Lunglei",
            "Mamit",
            "Saiha",
            "Serchhip",
            "Hnahthial",
            "Khawzawl",
            "Saitual",
        ],
    },
    Nagaland: {
        cities: [
            "Kohima",
            "Dimapur",
            "Mokokchung",
            "Tuensang",
            "Wokha",
            "Zunheboto",
            "Phek",
            "Mon",
            "Kiphire",
            "Longleng",
            "Peren",
        ],
        districts: [
            "Dimapur",
            "Kiphire",
            "Kohima",
            "Longleng",
            "Mokokchung",
            "Mon",
            "Peren",
            "Phek",
            "Tuensang",
            "Wokha",
            "Zunheboto",
        ],
    },
    Sikkim: {
        cities: [
            "Gangtok",
            "Namchi",
            "Geyzing",
            "Mangan",
            "Rangpo",
            "Jorethang",
            "Singtam",
            "Ravangla",
        ],
        districts: [
            "East Sikkim",
            "North Sikkim",
            "South Sikkim",
            "West Sikkim",
        ],
    },
    Tripura: {
        cities: [
            "Agartala",
            "Udaipur",
            "Dharmanagar",
            "Kailasahar",
            "Belonia",
            "Khowai",
            "Ambassa",
            "Teliamura",
            "Sabroom",
            "Sonamura",
        ],
        districts: [
            "Dhalai",
            "Gomati",
            "Khowai",
            "North Tripura",
            "Sepahijala",
            "South Tripura",
            "Unakoti",
            "West Tripura",
        ],
    },
    "Madhya Pradesh": {
        cities: [
            "Indore",
            "Bhopal",
            "Jabalpur",
            "Gwalior",
            "Ujjain",
            "Sagar",
            "Dewas",
            "Satna",
            "Ratlam",
            "Rewa",
            "Katni",
            "Singrauli",
            "Burhanpur",
            "Khandwa",
            "Bhind",
            "Chhindwara",
            "Guna",
            "Shivpuri",
            "Vidisha",
            "Damoh",
            "Mandsaur",
            "Khargone",
            "Neemuch",
            "Pithampur",
            "Hoshangabad",
            "Itarsi",
            "Sehore",
            "Betul",
            "Seoni",
            "Datia",
            "Nagda",
            "Dhar",
        ],
        districts: [
            "Agar Malwa",
            "Alirajpur",
            "Anuppur",
            "Ashoknagar",
            "Balaghat",
            "Barwani",
            "Betul",
            "Bhind",
            "Bhopal",
            "Burhanpur",
            "Chhatarpur",
            "Chhindwara",
            "Damoh",
            "Datia",
            "Dewas",
            "Dhar",
            "Dindori",
            "Guna",
            "Gwalior",
            "Harda",
            "Hoshangabad",
            "Indore",
            "Jabalpur",
            "Jhabua",
            "Katni",
            "Khandwa",
            "Khargone",
            "Mandla",
            "Mandsaur",
            "Morena",
            "Narsinghpur",
            "Neemuch",
            "Panna",
            "Raisen",
            "Rajgarh",
            "Ratlam",
            "Rewa",
            "Sagar",
            "Satna",
            "Sehore",
            "Seoni",
            "Shahdol",
            "Shajapur",
            "Sheopur",
            "Shivpuri",
            "Sidhi",
            "Singrauli",
            "Tikamgarh",
            "Ujjain",
            "Umaria",
            "Vidisha",
        ],
    },
    Odisha: {
        cities: [
            "Bhubaneswar",
            "Cuttack",
            "Rourkela",
            "Brahmapur",
            "Sambalpur",
            "Puri",
            "Balasore",
            "Bhadrak",
            "Baripada",
            "Jharsuguda",
            "Jeypore",
            "Bargarh",
            "Rayagada",
            "Balangir",
            "Bhawanipatna",
            "Dhenkanal",
            "Barbil",
            "Kendujhar",
            "Angul",
            "Talcher",
            "Paradip",
            "Bhuban",
        ],
        districts: [
            "Angul",
            "Balangir",
            "Balasore",
            "Bargarh",
            "Bhadrak",
            "Boudh",
            "Cuttack",
            "Deogarh",
            "Dhenkanal",
            "Gajapati",
            "Ganjam",
            "Jagatsinghpur",
            "Jajpur",
            "Jharsuguda",
            "Kalahandi",
            "Kandhamal",
            "Kendrapara",
            "Kendujhar",
            "Khordha",
            "Koraput",
            "Malkangiri",
            "Mayurbhanj",
            "Nabarangpur",
            "Nayagarh",
            "Nuapada",
            "Puri",
            "Rayagada",
            "Sambalpur",
            "Subarnapur",
            "Sundargarh",
        ],
    },
    Punjab: {
        cities: [
            "Ludhiana",
            "Amritsar",
            "Jalandhar",
            "Patiala",
            "Bathinda",
            "Mohali",
            "Hoshiarpur",
            "Batala",
            "Pathankot",
            "Moga",
            "Abohar",
            "Malerkotla",
            "Khanna",
            "Phagwara",
            "Muktsar",
            "Barnala",
            "Rajpura",
            "Firozpur",
            "Kapurthala",
            "Sangrur",
            "Fazilka",
            "Gurdaspur",
            "Kharar",
            "Gobindgarh",
            "Mansa",
            "Malout",
            "Nabha",
            "Tarn Taran",
            "Jagraon",
            "Sunam",
        ],
        districts: [
            "Amritsar",
            "Barnala",
            "Bathinda",
            "Faridkot",
            "Fatehgarh Sahib",
            "Fazilka",
            "Ferozepur",
            "Gurdaspur",
            "Hoshiarpur",
            "Jalandhar",
            "Kapurthala",
            "Ludhiana",
            "Mansa",
            "Moga",
            "Mohali",
            "Muktsar",
            "Pathankot",
            "Patiala",
            "Rupnagar",
            "Sangrur",
            "Shaheed Bhagat Singh Nagar",
            "Tarn Taran",
        ],
    },
    Rajasthan: {
        cities: [
            "Jaipur",
            "Jodhpur",
            "Kota",
            "Bikaner",
            "Ajmer",
            "Udaipur",
            "Bhilwara",
            "Alwar",
            "Bharatpur",
            "Pali",
            "Barmer",
            "Sikar",
            "Tonk",
            "Sadulpur",
            "Sawai Madhopur",
            "Hanumangarh",
            "Gangapur City",
            "Churu",
            "Dhaulpur",
            "Sri Ganganagar",
            "Chittorgarh",
            "Beawar",
            "Kishangarh",
            "Bundi",
            "Jhunjhunu",
            "Hindaun",
            "Nagaur",
            "Makrana",
            "Sujangarh",
            "Sardarshahar",
        ],
        districts: [
            "Ajmer",
            "Alwar",
            "Banswara",
            "Baran",
            "Barmer",
            "Bharatpur",
            "Bhilwara",
            "Bikaner",
            "Bundi",
            "Chittorgarh",
            "Churu",
            "Dausa",
            "Dholpur",
            "Dungarpur",
            "Hanumangarh",
            "Jaipur",
            "Jaisalmer",
            "Jalore",
            "Jhalawar",
            "Jhunjhunu",
            "Jodhpur",
            "Karauli",
            "Kota",
            "Nagaur",
            "Pali",
            "Pratapgarh",
            "Rajsamand",
            "Sawai Madhopur",
            "Sikar",
            "Sirohi",
            "Sri Ganganagar",
            "Tonk",
            "Udaipur",
        ],
    },
    "Tamil Nadu": {
        cities: [
            "Chennai",
            "Coimbatore",
            "Madurai",
            "Tiruchirappalli",
            "Salem",
            "Tirunelveli",
            "Tiruppur",
            "Ranipet",
            "Nagercoil",
            "Thanjavur",
            "Vellore",
            "Kancheepuram",
            "Erode",
            "Tiruvannamalai",
            "Pollachi",
            "Rajapalayam",
            "Sivakasi",
            "Pudukkottai",
            "Neyveli",
            "Nagapattinam",
            "Viluppuram",
            "Tiruvallur",
            "Karur",
            "Cuddalore",
            "Kumbakonam",
            "Tirupur",
            "Avadi",
            "Tambaram",
            "Ambattur",
        ],
        districts: [
            "Ariyalur",
            "Chengalpattu",
            "Chennai",
            "Coimbatore",
            "Cuddalore",
            "Dharmapuri",
            "Dindigul",
            "Erode",
            "Kallakurichi",
            "Kanchipuram",
            "Kanyakumari",
            "Karur",
            "Krishnagiri",
            "Madurai",
            "Mayiladuthurai",
            "Nagapattinam",
            "Namakkal",
            "Nilgiris",
            "Perambalur",
            "Pudukkottai",
            "Ramanathapuram",
            "Ranipet",
            "Salem",
            "Sivaganga",
            "Tenkasi",
            "Thanjavur",
            "Theni",
            "Thoothukudi",
            "Tiruchirappalli",
            "Tirunelveli",
            "Tirupathur",
            "Tiruppur",
            "Tiruvallur",
            "Tiruvannamalai",
            "Tiruvarur",
            "Vellore",
            "Viluppuram",
            "Virudhunagar",
        ],
    },
    Telangana: {
        cities: [
            "Hyderabad",
            "Warangal",
            "Nizamabad",
            "Karimnagar",
            "Ramagundam",
            "Khammam",
            "Mahbubnagar",
            "Nalgonda",
            "Adilabad",
            "Suryapet",
            "Siddipet",
            "Miryalaguda",
            "Jagtial",
            "Mancherial",
            "Nirmal",
            "Kothagudem",
            "Bodhan",
            "Sangareddy",
            "Metpally",
            "Zahirabad",
            "Medak",
            "Gadwal",
            "Wanaparthy",
            "Bhongir",
        ],
        districts: [
            "Adilabad",
            "Bhadradri Kothagudem",
            "Hyderabad",
            "Jagtial",
            "Jangaon",
            "Jayashankar",
            "Jogulamba",
            "Kamareddy",
            "Karimnagar",
            "Khammam",
            "Komaram Bheem",
            "Mahabubabad",
            "Mahbubnagar",
            "Mancherial",
            "Medak",
            "Medchal",
            "Nagarkurnool",
            "Nalgonda",
            "Nirmal",
            "Nizamabad",
            "Peddapalli",
            "Rajanna Sircilla",
            "Rangareddy",
            "Sangareddy",
            "Siddipet",
            "Suryapet",
            "Vikarabad",
            "Wanaparthy",
            "Warangal Rural",
            "Warangal Urban",
            "Yadadri Bhuvanagiri",
        ],
    },
    "Uttar Pradesh": {
        cities: [
            "Lucknow",
            "Kanpur",
            "Ghaziabad",
            "Agra",
            "Varanasi",
            "Meerut",
            "Allahabad",
            "Bareilly",
            "Aligarh",
            "Moradabad",
            "Saharanpur",
            "Gorakhpur",
            "Noida",
            "Firozabad",
            "Jhansi",
            "Muzaffarnagar",
            "Mathura",
            "Rampur",
            "Shahjahanpur",
            "Farrukhabad",
            "Ayodhya",
            "Maunath Bhanjan",
            "Hapur",
            "Etawah",
            "Mirzapur",
            "Bulandshahr",
            "Sambhal",
            "Amroha",
            "Hardoi",
            "Fatehpur",
            "Raebareli",
            "Orai",
            "Sitapur",
            "Bahraich",
            "Modinagar",
            "Unnao",
            "Jaunpur",
            "Lakhimpur",
            "Hathras",
            "Banda",
            "Pilibhit",
            "Barabanki",
            "Khurja",
            "Gonda",
            "Mainpuri",
            "Lalitpur",
            "Etah",
            "Deoria",
            "Ujhani",
            "Ghazipur",
            "Sultanpur",
            "Azamgarh",
            "Bijnor",
            "Sahaswan",
            "Basti",
            "Chandausi",
            "Akbarpur",
            "Ballia",
            "Tanda",
            "Greater Noida",
            "Shikohabad",
            "Shamli",
            "Awagarh",
            "Kasganj",
        ],
        districts: [
            "Agra",
            "Aligarh",
            "Ambedkar Nagar",
            "Amethi",
            "Amroha",
            "Auraiya",
            "Ayodhya",
            "Azamgarh",
            "Baghpat",
            "Bahraich",
            "Ballia",
            "Balrampur",
            "Banda",
            "Barabanki",
            "Bareilly",
            "Basti",
            "Bhadohi",
            "Bijnor",
            "Budaun",
            "Bulandshahr",
            "Chandauli",
            "Chitrakoot",
            "Deoria",
            "Etah",
            "Etawah",
            "Farrukhabad",
            "Fatehpur",
            "Firozabad",
            "Gautam Buddha Nagar",
            "Ghaziabad",
            "Ghazipur",
            "Gonda",
            "Gorakhpur",
            "Hamirpur",
            "Hapur",
            "Hardoi",
            "Hathras",
            "Jalaun",
            "Jaunpur",
            "Jhansi",
            "Kannauj",
            "Kanpur Dehat",
            "Kanpur Nagar",
            "Kasganj",
            "Kaushambi",
            "Kushinagar",
            "Lakhimpur Kheri",
            "Lalitpur",
            "Lucknow",
            "Maharajganj",
            "Mahoba",
            "Mainpuri",
            "Mathura",
            "Mau",
            "Meerut",
            "Mirzapur",
            "Moradabad",
            "Muzaffarnagar",
            "Pilibhit",
            "Pratapgarh",
            "Prayagraj",
            "Raebareli",
            "Rampur",
            "Saharanpur",
            "Sambhal",
            "Sant Kabir Nagar",
            "Shahjahanpur",
            "Shamli",
            "Shravasti",
            "Siddharthnagar",
            "Sitapur",
            "Sonbhadra",
            "Sultanpur",
            "Unnao",
            "Varanasi",
        ],
    },
    Uttarakhand: {
        cities: [
            "Dehradun",
            "Haridwar",
            "Roorkee",
            "Haldwani",
            "Rudrapur",
            "Kashipur",
            "Rishikesh",
            "Pithoragarh",
            "Ramnagar",
            "Manglaur",
            "Nainital",
            "Mussoorie",
            "Tehri",
            "Pauri",
            "Nagla",
            "Sitarganj",
            "Bageshwar",
            "Almora",
            "Champawat",
            "Rudraprayag",
            "Kotdwar",
            "Tanakpur",
            "Jaspur",
            "Vikasnagar",
        ],
        districts: [
            "Almora",
            "Bageshwar",
            "Chamoli",
            "Champawat",
            "Dehradun",
            "Haridwar",
            "Nainital",
            "Pauri Garhwal",
            "Pithoragarh",
            "Rudraprayag",
            "Tehri Garhwal",
            "Udham Singh Nagar",
            "Uttarkashi",
        ],
    },
    "West Bengal": {
        cities: [
            "Kolkata",
            "Asansol",
            "Siliguri",
            "Durgapur",
            "Bardhaman",
            "Malda",
            "Baharampur",
            "Habra",
            "Kharagpur",
            "Shantipur",
            "Dankuni",
            "Dhulian",
            "Ranaghat",
            "Haldia",
            "Raiganj",
            "Krishnanagar",
            "Nabadwip",
            "Medinipur",
            "Jalpaiguri",
            "Balurghat",
            "Basirhat",
            "Bankura",
            "Chakdaha",
            "Darjeeling",
            "Alipurduar",
            "Purulia",
            "Jangipur",
            "Bolpur",
            "Bangaon",
            "CoochBehar",
        ],
        districts: [
            "Alipurduar",
            "Bankura",
            "Birbhum",
            "Cooch Behar",
            "Dakshin Dinajpur",
            "Darjeeling",
            "Hooghly",
            "Howrah",
            "Jalpaiguri",
            "Jhargram",
            "Kalimpong",
            "Kolkata",
            "Malda",
            "Murshidabad",
            "Nadia",
            "North 24 Parganas",
            "Paschim Bardhaman",
            "Paschim Medinipur",
            "Purba Bardhaman",
            "Purba Medinipur",
            "Purulia",
            "South 24 Parganas",
            "Uttar Dinajpur",
        ],
    },
    "Andaman and Nicobar Islands": {
        cities: [
            "Port Blair",
            "Diglipur",
            "Rangat",
            "Mayabunder",
            "Car Nicobar",
            "Nancowry",
            "Campbell Bay",
        ],
        districts: ["Nicobar", "North and Middle Andaman", "South Andaman"],
    },
    Chandigarh: {
        cities: ["Chandigarh"],
        districts: ["Chandigarh"],
    },
    "Dadra and Nagar Haveli and Daman and Diu": {
        cities: ["Daman", "Diu", "Silvassa"],
        districts: ["Dadra and Nagar Haveli", "Daman", "Diu"],
    },
    Lakshadweep: {
        cities: ["Kavaratti", "Agatti", "Minicoy", "Amini", "Andrott"],
        districts: ["Lakshadweep"],
    },
    Puducherry: {
        cities: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
        districts: ["Karaikal", "Mahe", "Puducherry", "Yanam"],
    },
    "Jammu and Kashmir": {
        cities: [
            "Srinagar",
            "Jammu",
            "Anantnag",
            "Baramulla",
            "Sopore",
            "Kathua",
            "Udhampur",
            "Punch",
            "Rajauri",
            "Kupwara",
            "Bandipore",
            "Pulwama",
            "Ganderbal",
            "Budgam",
            "Kulgam",
            "Shopian",
            "Bandipora",
            "Doda",
            "Kishtwar",
            "Ramban",
            "Reasi",
            "Samba",
        ],
        districts: [
            "Anantnag",
            "Bandipora",
            "Baramulla",
            "Budgam",
            "Doda",
            "Ganderbal",
            "Jammu",
            "Kathua",
            "Kishtwar",
            "Kulgam",
            "Kupwara",
            "Poonch",
            "Pulwama",
            "Rajouri",
            "Ramban",
            "Reasi",
            "Samba",
            "Shopian",
            "Srinagar",
            "Udhampur",
        ],
    },
    Ladakh: {
        cities: [
            "Leh",
            "Kargil",
            "Nubra",
            "Zanskar",
            "Diskit",
            "Panamik",
            "Drass",
        ],
        districts: ["Kargil", "Leh"],
    },
};

console.log("✅ All remaining Indian states data prepared");
console.log(`📊 Total states to add: ${Object.keys(remainingStates).length}`);
console.log("\n📝 Copy this data and add it to app/api/locations/route.ts");
console.log("\nStates included:");
Object.keys(remainingStates).forEach((state) => {
    const data = remainingStates[state as keyof typeof remainingStates];
    console.log(
        `  - ${state}: ${data.cities.length} cities, ${data.districts.length} districts`
    );
});
